---
- name: install Mosh package for Debian-based system
  apt: name={{mosh_pkg}} state=present
  when: ansible_os_family == 'Debian' and (not mosh_debian_use_backports)

- name: install Mosh package for Debian-based system from backports
  apt: name={{mosh_pkg}} state=present default_release={{mosh_debian_backports_target}}
  when: ansible_os_family == 'Debian' and mosh_debian_use_backports

- name: install Mosh package for Debian-based system
  apt: name={{mosh_pkg}} state=present
  when: ansible_os_family == 'Debian'

- name: install Mosh package for openSuSE
  zypper: name={{mosh_pkg}} state=present
  when: ansible_distribution == 'opensuse'

- name: install Mosh package for Fedora
  yum: name={{mosh_pkg}} state=present
  when: ansible_distribution == 'Fedora'
